package tn.esprit.entities;

public enum RecoveryPlanGoal {
    REHABILITATION,
    PREVENTION,
    PERFORMANCE_OPTIMIZATION,
    PAIN_MANAGEMENT,
    STRENGTHENING,
    MOBILITY_RESTORATION,
    ENDURANCE_BUILDING,
    FUNCTIONAL_RECOVERY,
    PSYCHOSOCIAL_RECOVERY
}
